version: '3'
services: 
    tosdev:
        container_name: tosdev
        build: 
            context: .
            dockerfile: dockerfile-dev
        ports:
            - "8200:8000"
        volumes:
            - ./input:/var/www/base/tos-parser/input/
            