version: '3'
services: 
    tosrepatch:
       
        build: 
            context: .
            dockerfile: dockerfile
            args:
                - SERVICE_NAME=$SERVICE_NAME
                - LOCAL_GID=$LOCAL_GID
                - LOCAL_UID=$LOCAL_UID
        command: /bin/bash /var/www/base/build.sh 1 
        
        volumes:
            - ./input:/var/www/base/tos-parser/input
            