version: '3'
services: 
    tosrepatch:
       
        build: 
            context: .
            dockerfile: dockerfile
        command: /bin/bash /var/www/base/build.sh 1 
        args:
            - SERVICE_NAME=$SERVICE_NAME
        volumes:
            - ./input:/var/www/base/tos-parser/input
            