version: '3'
services: 
    tos:
        container_name: tos
        build: 
            context: .
            dockerfile: dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./input:/var/www/base/tos-parser/input/