version: '3'
services: 
    tos:
        container_name: tos
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./input:/var/www/base/tos-parser/input/
            - ./distweb:/var/www/base/tos-web/dist/
            - ./distbuild:/var/www/base/tos-build/dist/