version: '3'
services: 
    tosdev:
        container_name: tosdev
        build: .
        ports:
            - "8200:8000"
        volumes:
            - ./input:/var/www/base/tos-parser/input/
            - ./distweb:/var/www/base/tos-web/dist/
            - ./distbuild:/var/www/base/tos-build/dist/
            