version: '3'
services: 
    tos:
        container_name: tos
        build: 
            context: .
            dockerfile: dockerfile
            args:
                - SERVICE_NAME=$SERVICE_NAME
                - LOCAL_GID=$LOCAL_GID
                - LOCAL_UID=$LOCAL_UID
        restart: always
       
        ports:
            - "8000:80"
        volumes:
            - ./input:/var/www/base/tos-parser/input/