version: '3'
services: 
    tos:
        container_name: tos
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./input:/var/www/base/tos-parser/input/
           
            