version: '3'
services: 
    tosdev:
        container_name: tosdev
        build: 
            context: .
            dockerfile: dockerfile
        restart: always
        ports:
            - "8200:80"
        volumes:
            - ./input:/var/www/base/tos-parser/input
            